# Generated by Django 3.2.13 on 2022-07-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicBank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
