# Generated by Django 3.2.13 on 2022-07-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicBank', '0002_alter_customerdetail_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200, null=True)),
                ('reciever', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('date_tran', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
